#!/bin/sh
set -ev

#git config --global user.name "Travis CI"
#git config --global user.email "rick1987@gmail.com"
#git remote set-url origin https://ricsp:${GH_TOKEN}@github.com/ricsp/vrep_ros_bridge
#git fetch origin gh-pages:gh-pages
